# Generated by Django 5.1.4 on 2026-02-27 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_ID', models.AutoField(primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=255)),
                ('e_mail', models.EmailField(max_length=255)),
                ('DOB', models.DateField()),
                ('date_of_creation', models.DateField(auto_now_add=True)),
                ('account_image', models.ImageField(upload_to='accounts/')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_ID', models.AutoField(primary_key=True, serialize=False)),
                ('artist_name', models.CharField(max_length=255)),
                ('artist_image', models.ImageField(upload_to='artist/')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publisher_ID', models.AutoField(primary_key=True, serialize=False)),
                ('publisher_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('playlist_ID', models.AutoField(primary_key=True, serialize=False)),
                ('playlist_name', models.CharField(max_length=255)),
                ('playlist_image', models.ImageField(upload_to='playlist/')),
                ('owner_account_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_app.account')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('album_ID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('album_image', models.ImageField(upload_to='album/')),
                ('artist_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_app.artist')),
                ('publisher_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_app.publisher')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('spotify_URL', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('track_name', models.CharField(max_length=255)),
                ('track_number', models.PositiveIntegerField()),
                ('explicit', models.BooleanField()),
                ('duration', models.PositiveIntegerField()),
                ('tempo', models.PositiveIntegerField()),
                ('time_signature', models.PositiveIntegerField()),
                ('album_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_app.album')),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive_app.account')),
                ('playlist_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_app.playlist')),
                ('spotify_URL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_app.track')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('playlist_ID', 'spotify_URL'), name='playlist_track_PK')],
            },
        ),
        migrations.CreateModel(
            name='TrackArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PRIMARY', 'Primary artist'), ('OTHER', 'Other artist')], max_length=7)),
                ('artist_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_app.artist')),
                ('spotify_URL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_app.track')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('spotify_URL', 'artist_ID'), name='track_artist_PK')],
            },
        ),
    ]
