# Generated by Django 6.0.2 on 2026-03-17 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('artist_name', models.CharField(max_length=255)),
                ('artist_image', models.ImageField(upload_to='artist/')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('account_name', models.CharField(max_length=255)),
                ('DOB', models.DateField()),
                ('profile_image', models.ImageField(upload_to='Profiles/')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('album_ID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('album_image', models.ImageField(upload_to='album/')),
                ('artist_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_app.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('spotify_URL', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('track_name', models.CharField(max_length=255)),
                ('track_number', models.PositiveIntegerField()),
                ('explicit', models.BooleanField()),
                ('duration', models.PositiveIntegerField()),
                ('tempo', models.PositiveIntegerField()),
                ('time_signature', models.PositiveIntegerField()),
                ('album_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_app.album')),
            ],
        ),
        migrations.CreateModel(
            name='TrackArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PRIMARY', 'Primary artist'), ('OTHER', 'Other artist')], max_length=7)),
                ('artist_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_app.artist')),
                ('spotify_URL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_app.track')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('spotify_URL', 'artist_ID'), name='track_artist_PK')],
            },
        ),
    ]
