# Generated by Django 5.1.4 on 2026-02-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='e_mail',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
