# Generated by Django 6.0.2 on 2026-02-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_app', '0002_alter_account_e_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='password_hash',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='e_mail',
            field=models.EmailField(error_messages={'unique': 'Email already registered. Log in instead.'}, max_length=255, unique=True),
        ),
    ]
